pyrpl: # General configuration of the software:
  name: test_refactor
  gui: true # autostart gui
  loglevel: info
  # level of logged information.
  # 'debug' outputs everything
  # 'infi' is default level
  # 'warning' only shows warnings and errors
  # 'error' only shows errors
  modules: # SoftwareModules to load (in addition to IqManager, AsgManager, PidManager, ScopeManager)
    - NetworkAnalyzer
    - SpectrumAnalyzer
redpitaya:
  password: root
  user: root
  port: 2222
  frequency_correction: 1.0
  filename: fpga//red_pitaya.bin
  reloadfpga: true
  monitor_server_name: monitor_server